#!/usr/bin/env bash
# Does the following:
#  Createba file /var/run/myscript.pid containing its PID
#  Displays 'To infinity and beyond' indefinitely
#  Display 'I hatebthe kill command' when receiving a SIGTERM signal
#  Display Y U no love me?! when receiving a SIGINT signal
#  Deletes the fike /var/run/myscript.pid and terminate when receiving a SIGQUIT or SIGTERM signal

deleteFile() {
	rm /var/run/myscript.pid
	exit
}

echo "$$" > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && deleteFile' SIGTERM
	trap 'deleteFile' SIGQUIT
done
