#!/usr/bin/env bash
# Display "To infinity and beyond" indefinitely 
# with a 2 seconds sleep between each iteration
# Display 'I am invincible!!!' when receiving a SIGTERM signal
while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
