#!/usr/bin/env bash
# Display numbers from 1 to 100 in list format
# "fizbuzz when the number is a multiple of 3 and 5
# "fizz" when the number is a multiple of 3
# "buzz' when the number is a multiple of 5
# otherwise, the number

for num in {1..100}
do
	if (( num % 3 == 0 && num % 5 == 0 ))
	then
		echo "fizzbuzz"
	elif (( num % 3 == 0 ))
	then
		echo "fizz"
	elif (( num % 5 == 0 ))
	then
		echo "buzz"
	else
		echo $num
	fi
done
