#!/usr/bin/env bash
# Display the content of the file `/etc/passwd`
# Only display the username, user id, and user home directory path

while read passwd;
do
	echo "$passwd"| cut -d ':' -f1,3,6
done < "/etc/passwd"
