#!/usr/bin/env bash
# Parses Apache log files in list format.
#  Group visiitoors by IP and HTTP status code.
#  Diisplay the number of occurrence, IP, and HTTP status
#  coode of ech log, in sorted order

awk '{print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
