#!/usr/bin/env bash
# Display "Best School" 10 times using a while loop and if condition

count=0

while [ $count -lt 10 ]
do
	echo "Best School"
	(( count++))
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
done
