#!/usr/bin/env bash
# Display the content of the current directory in list format
# only display the part of the name afterbthe first dash

list=$(ls)
for i in $list;
do
	echo "$i" | cut -d '-' -f2
done
